#ifndef RANDOM_HLSL
#define RANDOM_HLSL

#include "Common.hlsli"

// ============================================================
// PCG
// ============================================================

#define PCGSeed uint4

// Source: "Hash Functions for GPU Rendering" by Jarzynski & Olano
PCGSeed pcg4d(PCGSeed v)
{
    v = v * 1664525u + 1013904223u;

    v.x += v.y * v.w;
    v.y += v.z * v.x;
    v.z += v.x * v.y;
    v.w += v.y * v.z;

    v = v ^ (v >> 16u);

    v.x += v.y * v.w;
    v.y += v.z * v.x;
    v.z += v.x * v.y;
    v.w += v.y * v.z;

    return v;
}

float PCGRand(inout PCGSeed seed)
{
    seed.w++;
    return UIntToFloat(pcg4d(seed).x);
}

float2 PCGRand2(inout PCGSeed seed)
{
    return float2(PCGRand(seed), PCGRand(seed));
}

// Seed for PCG uses a sequential sample number in 4th channel, which increments on every RNG call and starts from 0
PCGSeed PCGInitSeed(uint2 pixel, uint frameIndex)
{
    return PCGSeed(pixel, frameIndex, 0);
}

// ============================================================
// Owen-scrambled Sobol
// Source: Burley 2020, "Practical Hash-based Owen Scrambling", JCGT
// ============================================================

#define SobolSeed uint4

#ifndef HILBERT_SIZE
#define HILBERT_SIZE 128u // Hilbert curve size (must be power of 2). Larger = better low-discrepancy but worse blue-noise.
#endif // HILBERT_SIZE

// Sobol direction vectors for dimension 1
// Primitive polynomial: x+1 (s=1, a=0, m=[1])
// Generated by: V[0] = 2^31, V[i] = V[i-1] ^ (V[i-1] >> 1)
static const uint SOBOL_V1[32] =
{
    0x80000000u, 0xC0000000u, 0xA0000000u, 0xF0000000u,
    0x88000000u, 0xCC000000u, 0xAA000000u, 0xFF000000u,
    0x80800000u, 0xC0C00000u, 0xA0A00000u, 0xF0F00000u,
    0x88880000u, 0xCCCC0000u, 0xAAAA0000u, 0xFFFF0000u,
    0x80008000u, 0xC000C000u, 0xA000A000u, 0xF000F000u,
    0x88008800u, 0xCC00CC00u, 0xAA00AA00u, 0xFF00FF00u,
    0x80808080u, 0xC0C0C0C0u, 0xA0A0A0A0u, 0xF0F0F0F0u,
    0x88888888u, 0xCCCCCCCCu, 0xAAAAAAAAu, 0xFFFFFFFFu
};

// Maps a 2D pixel coordinate to its index along a Hilbert space-filling curve.
// Spatial proximity in screen space → nearby indices → good blue noise distribution
// after Owen scrambling (nearby indices stay well-spread across [0,1)).
uint HilbertIndex(uint2 pos, uint n)
{
    uint index = 0u;
    for (uint curLevel = n >> 1u; curLevel > 0u; curLevel >>= 1u)
    {
        uint regionX = (pos.x & curLevel) > 0u ? 1u : 0u;
        uint regionY = (pos.y & curLevel) > 0u ? 1u : 0u;
        index += curLevel * curLevel * ((3u * regionX) ^ regionY);
        if (regionY == 0u)
        {
            if (regionX == 1u)
            {
                pos.x = n - 1u - pos.x;
                pos.y = n - 1u - pos.y;
            }
            uint t = pos.x;
            pos.x = pos.y;
            pos.y = t;
        }
    }
    return index;
}

// Laine-Karras permutation — the hash behind Owen scrambling
// Improved version: https://psychopath.io/post/2021_01_30_building_a_better_lk_hash
uint LKPermutation(uint x, uint seed)
{
    x ^= x * 0x3d20adea;
    x += seed;
    x *= (seed >> 16) | 1;
    x ^= x * 0x05526c56;
    x ^= x * 0x53a22864;
    return x;
}

uint HashCombine(uint seed, uint v)
{
    return seed ^ (v + (seed << 6) + (seed >> 2));
}

float HashToFloat01(uint x)
{
    return (x & 0x00FFFFFFu) * (1.0 / 16777216.0);
}

float2 HashToFloat2(uint s)
{
    uint h1 = LKPermutation(s, 0xA511E9B3u);
    uint h2 = LKPermutation(s, 0x63D83595u);
    return float2(HashToFloat01(h1), HashToFloat01(h2));
}

// Nested uniform scramble = Owen scrambling via bit-reversal sandwiching
uint NestedUniformScramble(uint x, uint seed)
{
    x = reversebits(x);
    x = LKPermutation(x, seed);
    x = reversebits(x);
    return x;
}

// Raw Sobol sample
uint SobolUint(uint index)
{
    uint result = 0;
    [unroll]
    for (uint bit = 0; bit < 32; bit++)
    {
        int mask = (index >> bit) & 1;
        result ^= mask * SOBOL_V1[bit];
    }
    return result;
}

SobolSeed SobolInitSeed(uint2 pixel, uint frameIndex)
{
    uint2 tilePixel = pixel & (HILBERT_SIZE - 1u);
    uint h = HilbertIndex(tilePixel, HILBERT_SIZE);

    SobolSeed seed;
    seed.x = LKPermutation(h, 0xA9E3F1C7u);
    seed.y = frameIndex;
    seed.z = 0u;
    seed.w = 0u;
    return seed;
}

float SobolRand(inout SobolSeed seed)
{
    uint dim     = seed.z++;
    uint dimPair = dim >> 1u;
    uint isOdd   = dim & 1u;
    
    uint pairSeed = HashCombine(seed.x, dimPair);
    uint scrambledIndex = NestedUniformScramble(seed.y, pairSeed);

    // Dimension 0 of each pair = Van der Corput (reversebits)
    // Dimension 1 of each pair = SOBOL_V1 direction vectors
    uint valueSeed = LKPermutation(pairSeed, isOdd ? 0x9E3779B9u : 0x85EBCA6Bu);
    uint sobolValue = isOdd ? SobolUint(scrambledIndex) : reversebits(scrambledIndex);
    return UIntToFloat(NestedUniformScramble(sobolValue, valueSeed));
}

float2 SobolRand2(inout SobolSeed seed)
{
    return float2(SobolRand(seed), SobolRand(seed));
}

#endif // RANDOM_HLSL
